### PR TITLE
Added caffe-theano-keras-cuda directory

### PR DESCRIPTION
**Pull request by karllab41**

### CODE REVIEW

**Comment by kylef-lab41** [comment]
nice addition.  you may want to eventually clean up some of those hanging comments, but otherwise this is solid.

**Comment by mikefreed** [comment]
I am out of the office until 10/05/2015.

I am on leave until 10/5.

Best,

Mike


Note: This is an automated response to your message  "Re: [sunny-side-up]
Added caffe-theano-keras-cuda directory (#41)" sent on 10/2/2015 6:35:24 PM
.

This is the only notification you will receive while this person is away.

**Comment by mikefreed** [comment]
I am out of the office until 10/05/2015.

I am on leave until 10/5.

Best,

Mike


Note: This is an automated response to your message  "[sunny-side-up] Added
caffe-theano-keras-cuda directory (#41)" sent on 10/2/2015 4:53:40 PM.

This is the only notification you will receive while this person is away.

**Comment by mikefreed** [comment]
I am out of the office until 10/05/2015.

I am on leave until 10/5.

Best,

Mike


Note: This is an automated response to your message  "Re: [sunny-side-up]
Added caffe-theano-keras-cuda directory (#41)" sent on 10/2/2015 6:35:21 PM
.

This is the only notification you will receive while this person is away.

**Pull request merged**
